version: "3"

services:

  cadvisor:
    image: google/cadvisor:latest
    command: -housekeeping_interval=1s -disable_metrics=disk,tcp -enable_load_reader 
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
#      - /dev/disk/:/dev/disk:ro
    ports:
      - "8888:8080"
